name: Test Deploy to Vercel
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  deployments: write
  pull-requests: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfontconfig-dev libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev libsoup-3.0-dev git build-essential
      - name: Format
        working-directory: apps/readest-app/src-tauri
        run: cargo fmt --check
      - name: Clippy Check
        working-directory: apps/readest-app/src-tauri
        run: cargo clippy -- -D warnings
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: install Dependencies
        working-directory: apps/readest-app
        run: |
          pnpm install && pnpm setup-pdfjs && pnpm install npx && pnpm install vercel
      - name: build the web App
        working-directory: apps/readest-app
        run: |
          pnpm build-web
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID}}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID}}
        # run: |
        #   pnpm build
        #   vercel deploy --prebuilt --prod --token ${VERCEL_TOKEN}
        with:
          working-directory: apps/readest-app
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
